Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2022-10, with the labels that each got.

#96 Make latest the default tag
  Makefile
  config/manager/kustomization.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#97 Add an extra label to the build job to label the stage of the build
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/constants/constants.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#108 Change all SRO references to KMM/modules
  api/v1beta1/preflightvalidation_types.go
  config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
  internal/metrics/metrics.go
  skipper.env
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#118 Modify Makefile in kmm-kmod
  ci/kmm-kmod/Makefile
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#123 Change the condition for node label deletion when ModuleLoader is del…
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
  controllers/pod_node_module_reconciler.go
Labels: size/M, approved, lgtm, cncf-cla: yes
