Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2022-09, with the labels that each got.

#24 Adding build option to disable pushes to registry
  controllers/module_reconciler.go
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/job/mock_maker.go
  internal/build/manager.go
  internal/build/mock_manager.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#29 Allow changing image's tag when building with kaniko
  api/v1beta1/module_types.go
  ci/module-kmm-ci-build.template.yaml
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  internal/build/job/maker.go
  internal/build/job/maker_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#32 Separate PullOption for build process and image verification
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  ci/module-kmm-ci-build.template.yaml
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  internal/build/helper.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/mock_helper.go
  internal/registry/mock_registry_api.go
  internal/registry/registry.go
  internal/registry/registry_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#36 Ignore mocks in test coverage report via codecov config
  .github/codecov.yml
  .github/workflows/test-build.yml
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#33 Separate in-cluster build and image existence verification
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  controllers/node_kernel_reconciler_test.go
  internal/build/helper.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/mock_helper.go
  internal/module/helper.go
  main.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#38 Fix the codecov config
  codecov.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#28 Fixing ci/prow/check-commit-count.
  ci/prow/check-commits-count
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#17 Load firmware from the module loader
  api/v1beta1/module_types.go
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#42 Moving authenticator creation to auth package
  controllers/module_reconciler.go
  internal/auth/auth.go
  internal/preflight/preflight.go
  internal/registry/registry.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#45 Add a build CI script
  ci/prow/build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#52 Preflight should use PullOptions in image verification
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/registry/mock_registry_api.go
  internal/registry/registry.go
  internal/registry/registry_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#50 Remove /usr/lib references at DaemonSet
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#39 Streamline GitHub Actions
  .github/workflows/test-build.yml
  .github/workflows/test-codecov.yml
  ci/prow/lint
Labels: size/M, approved, lgtm, cncf-cla: yes

#55 Add unit test guidelines in CONRIBUTING.md
  CONTRIBUTING.md
Labels: approved, lgtm, cncf-cla: yes, size/S

#57 Fix typo in unit test guidelines
  CONTRIBUTING.md
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#59 Adding 'ybettan' to the OWNERS file.
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#60 Fix config/manifests for bundle generation
  Makefile
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#65 adding build verification to preflight
  api/v1beta1/preflightvalidation_types.go
  config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
  controllers/preflightvalidation_reconciler.go
  controllers/preflightvalidation_reconciler_test.go
  internal/preflight/mock_preflight_api.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/registry/registry.go
  internal/registry/registry_test.go
  main.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#69 Improving some comment on the 'check-commit-count' job.
  ci/prow/check-commits-count
Labels: size/XS, approved, lgtm, cncf-cla: yes

#77 Trim plus sign in kernel versions
  controllers/module_reconciler.go
  controllers/node_kernel_reconciler.go
  controllers/node_kernel_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#56 Add the CloudBuild config to build images
  cloudbuild.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#76 Adding support for image push during preflight build verification
  api/v1beta1/preflightvalidation_types.go
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
  controllers/preflightvalidation_reconciler.go
  controllers/preflightvalidation_reconciler_test.go
  internal/filter/filter.go
  internal/preflight/mock_preflight_api.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#75 Replacing 'kustomize' binary with 'kubectl kustomize' binary.
  Makefile
Labels: approved, lgtm, cncf-cla: yes, size/S

#23 Add first document for lab
  docs/lab/README.md
  docs/lab/aws/dkms-kmm-kmod.yaml
  docs/lab/aws/kmm-kmod.yaml
  docs/lab/aws/ubuntu-kmm-kmod.yaml
  docs/lab/azure/kmm-kmod.yaml
  docs/lab/gce/alpine-kmm-driver.yaml
  docs/lab/gce/kmm-driver.yaml
  docs/lab/ubuntu/kmm-kmod.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#79 Add the -operator suffix to the image name
  Makefile
  ci/install-ci/kustomization.yaml
  config/manager/kustomization.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#81 Update of Build configuration in Module should trigger new Job
  config/rbac/role.yaml
  controllers/module_reconciler.go
  go.mod
  go.sum
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/job/mock_maker.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#85 Fixing build job deletion, in case its pods are still running
  internal/build/job/manager.go
  internal/build/job/manager_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#47 Update for kmm OWNERS
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#48 Update contacts
  SECURITY_CONTACTS
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#90 Add ServiceAccounts for the ModuleLoader and DevicePlugin workloads
  config/rbac/role.yaml
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/rbac/mock_rbac.go
  internal/rbac/rbac.go
  internal/rbac/rbac_test.go
  internal/rbac/suite_test.go
  main.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#92 Include .git in image builds
  .gcloudignore
Labels: size/XS, approved, lgtm, cncf-cla: yes

#88 centralise the name of the image to build in the controller
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/manager.go
  internal/build/mock_manager.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#91 add the fields for signing to crd
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test
