Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2022-12, with the labels that each got.

#166 Migrate e2e tests
  .github/actions/collect-troubleshooting/action.yml
  .github/workflows/e2e.yaml
  ci/prow/e2e-crd-variable
  ci/prow/e2e-incluster-build
  ci/prow/e2e-prebuilt-kernel-module
  ci/prow/e2e-prebuilt-kernel-module-two-nodes
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#165 Build signer images in CI
  Dockerfile.signimage
  Makefile
  cloudbuild.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#156 Decouple build and sign from ModuleReconciler
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/build/helper.go
  internal/build/helper_test.go
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/job/mock_maker.go
  internal/build/manager.go
  internal/build/mock_helper.go
  internal/build/mock_manager.go
  internal/module/helper.go
  internal/module/helper_test.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/sign/helper.go
  internal/sign/helper_test.go
  internal/sign/job/manager.go
  internal/sign/job/manager_test.go
  internal/sign/job/mock_signer.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
  internal/sign/manager.go
  internal/sign/mock_helper.go
  internal/sign/mock_manager.go
  internal/utils/jobhelper.go
  internal/utils/jobhelper_test.go
  internal/utils/mock_jobhelper.go
  main.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes, ok-to-test

#179 Fix module reconciler not being able to watch for ConfigMaps error
  config/rbac/role.yaml
  controllers/module_reconciler.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#162 Adding TLS options to the sign logic.
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager_test.go
  internal/module/helper.go
  internal/module/helper_test.go
  internal/preflight/preflight_test.go
  internal/sign/job/manager_test.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#180 add job watch to preflight controller setup
  controllers/preflightvalidation_reconciler.go
  internal/preflight/preflight.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#182 Build/Sign job selection should be done based on owner field also
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/manager.go
  internal/build/mock_manager.go
  internal/sign/job/manager.go
  internal/sign/job/manager_test.go
  internal/utils/jobhelper.go
  internal/utils/jobhelper_test.go
  internal/utils/mock_jobhelper.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#183 Fixing sign job hash annotation
  internal/constants/constants.go
  internal/sign/job/manager.go
  internal/sign/job/manager_test.go
  internal/sign/job/mock_signer.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
  main.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#186 Adding sign verification to the preflight flow
  api/v1beta1/preflightvalidation_types.go
  config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
  internal/module/helper.go
  internal/preflight/mock_preflight_api.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  main.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#189 Bump some dependencies
  Dockerfile.signimage
  go.mod
Labels: size/XS, approved, lgtm, cncf-cla: yes

#190 Fix logr.Error accepting key-value pair instead of error
  internal/filter/filter.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#191 Adjust ClusterClaim permissions to enable creation and caching
  config/rbac/role.yaml
  controllers/node_kernel_clusterclaim.go
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#178 Add build and sign in Hub for ManagedClusterModule reconciler
  api/v1beta1/managedclustermodule_types.go
  config/crd/bases/kmm.sigs.k8s.io_managedclustermodules.yaml
  controllers/managedclustermodule_reconciler.go
  controllers/managedclustermodule_reconciler_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster.go
  internal/cluster/suite_test.go
  internal/manifestwork/manifestwork.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
  internal/module/mock_kernelmapper.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes, ok-to-test

#202 Add PreflightValidation to the list of CRDs
  PROJECT
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#177 Fix example in labs
  docs/labs/gke/gke-ubuntu-nodes.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#208 Remove unused API in ModuleStatusUpdater
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
  main.go
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#214 Move to the `kmm.sigs.x-k8s.io` API group
  .github/workflows/e2e.yaml
  Makefile
  PROJECT
  api/v1beta1/groupversion_info.go
  ci/module-kmm-ci-build.template.yaml
  ci/module-kmm-ci-variable.yaml
  ci/module-kmm-ci.template.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_managedclustermodules.yaml
  config/crd/patches/cainjection_in_modules.yaml
  config/crd/patches/webhook_in_managedclustermodules.yaml
  config/crd/patches/webhook_in_modules.yaml
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
  config/rbac/managedclustermodule_editor_role.yaml
  config/rbac/managedclustermodule_viewer_role.yaml
  config/rbac/module_editor_role.yaml
  config/rbac/module_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kmm_v1alpha1_module.yaml
  config/samples/kmm_v1beta1_managedclustermodule.yaml
  controllers/managedclustermodule_reconciler.go
  controllers/module_reconciler.go
  controllers/preflightvalidation_reconciler.go
  docs/labs/aws/kmm-kmod.yaml
  docs/labs/azure/kmm-kmod.yaml
  docs/labs/gke/gke-ubuntu-nodes.yaml
  docs/labs/ubuntu/kmm-kmod.yaml
  internal/build/job/maker_test.go
  internal/sign/job/signer_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#213 Fixing FIRWARE files/directories loading
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#219 Installing `operator-skd` via Makefile.
  Makefile
Labels: approved, lgtm, cncf-cla: yes, size/S

#158 add user documentation for secureboot signing
  docs/mkdocs/secureboot/debugging.md
  docs/mkdocs/secureboot/index.md
  docs/mkdocs/secureboot/secureboot-build-and-sign.md
  docs/mkdocs/secureboot/secureboot-secrets.md
  docs/mkdocs/secureboot/secureboot-signing.md
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#221 Create ./bin when installing operator-sdk
  Makefile
  cloudbuild.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes
