Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2022-08, with the labels that each got.

#7 Add qbarrand to reviewers and approvers
  OWNERS
  ci/prow/lint
  ci/prow/unit-tests
Labels: size/XS, approved, lgtm, cncf-cla: yes

#8 Add yevgeny-shnaidman to approvers and reviewrs
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#18 Rename the operator name in README.md
  README.md
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#22 Remove the `docs` GitHub Actions.
  .github/workflows/docs.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#20 Adding a job that enforce a single commit for each PR.
  ci/prow/check-commits-count
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S
