Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2022-11, with the labels that each got.

#101 add code/dockerfile for building the secureboot signing job image
  Dockerfile.signimage
  Makefile
  cmd/signimage/README.md
  cmd/signimage/signimage.go
  internal/registry/mock_registry_api.go
  internal/registry/registry.go
  internal/registry/registry_helper_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#134 Fix OLM bundle failing because of incorrect CSV filename
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#136 Update skipper Dockerfile
  Dockerfile.kmm-operator-build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#127 Add EXTRA_MODULE variable to kmm-kmod Makefile
  ci/kmm-kmod/Makefile
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#133 Fix failing firmware requests
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#139 Add check-api-changes script to CI
  ci/prow/check-api-changes
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#149 Garbage collection for successfull build jobs
  .github/workflows/e2e.yaml
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/manager.go
  internal/build/mock_manager.go
  internal/constants/constants.go
  internal/sign/job/manager.go
  internal/sign/job/manager_test.go
  internal/utils/jobhelper.go
  internal/utils/jobhelper_test.go
  internal/utils/mock_jobhelper.go
  main.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#154 Remove unnecessary permissions on Module
  config/rbac/role.yaml
  controllers/module_reconciler.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#143 Enable configuration flags via component config
  config/default/kustomization.yaml
  config/manager/controller_manager_config.yaml
  main.go
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#142 Add code to the reconcile loop for signing of kmods for secureboot.
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/metrics/metrics.go
  internal/sign/job/manager.go
  internal/sign/job/manager_test.go
  main.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#130 Add and fix labs doc and examples
  README.md
  ci/kmm-kmod/dkms.conf
  docs/lab/aws/ubuntu-kmm-kmod.yaml
  docs/lab/gce/alpine-kmm-driver.yaml
  docs/lab/gce/kmm-driver.yaml
  docs/labs/README.md
  docs/labs/aws/dkms-kmm-kmod.yaml
  docs/labs/aws/kmm-kmod.yaml
  docs/labs/azure/kmm-kmod.yaml
  docs/labs/gke/gke-ubuntu-nodes.yaml
  docs/labs/ubuntu/kmm-kmod.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#160 Moving Build Dockerfile to be defined in the ConfigMap
  .github/workflows/e2e.yaml
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  ci/kmm-kmod-dockerfile.yaml
  ci/module-kmm-ci-build.template.yaml
  config/crd/bases/kmm.sigs.k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  config/rbac/role.yaml
  controllers/module_reconciler.go
  internal/build/helper.go
  internal/build/helper_test.go
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/job/mock_maker.go
  internal/constants/constants.go
  internal/module/kernelmapper_test.go
  main.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#86 Creating TLSOptions in favor of PullOptions and PushOptions.
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  ci/module-kmm-ci-build.template.yaml
  config/crd/bases/kmm.sigs.k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.k8s.io_modules.yaml
  controllers/module_reconciler.go
  internal/build/helper_test.go
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/job/mock_maker.go
  internal/module/helper.go
  internal/preflight/preflight.go
  internal/registry/mock_registry_api.go
  internal/registry/registry.go
  internal/registry/registry_test.go
  internal/sign/job/manager_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#163 Fixing a bug in the 'sign' UT.
  internal/sign/job/signer_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#168 Fix check-api-changes script
  ci/prow/check-api-changes
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#169 Add empty ManagedClusterModuleStatus to resolve operator-sdk error
  api/v1beta1/managedclustermodule_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.k8s.io_managedclustermodules.yaml
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#167 Update Labs examples with ConfigMaps
  docs/labs/README.md
  docs/labs/aws/build-configmap.yaml
  docs/labs/aws/build-dkms-configmap.yaml
  docs/labs/aws/dkms-kmm-kmod.yaml
  docs/labs/aws/kmm-kmod.yaml
  docs/labs/azure/build-configmap.yaml
  docs/labs/azure/kmm-kmod.yaml
  docs/labs/gke/build-configmap.yaml
  docs/labs/gke/gke-ubuntu-nodes.yaml
  docs/labs/ubuntu/build-module.yaml
  docs/labs/ubuntu/kmm-kmod.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#172 Fix check-api-changes
  ci/prow/check-api-changes
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#174 Pushing all missing generated files.
  bundle.Dockerfile
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#152 Add the kernel - ClusterClaim reconciler
  config/rbac/role.yaml
  controllers/node_kernel_clusterclaim.go
  controllers/node_kernel_clusterclaim_test.go
  internal/filter/filter.go
  internal/filter/filter_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes
