Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-03, with the labels that each got.

#313 Use kaniko for signing
  Dockerfile.signimage
  Makefile
  cmd/manager-hub/main.go
  cmd/manager/main.go
  cmd/signimage/README.md
  cmd/signimage/signimage.go
  internal/registry/mock_registry_api.go
  internal/registry/registry.go
  internal/sign/job/manager_test.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
  internal/sign/job/templates/Dockerfile.gotmpl
  internal/sign/suite_test.go
  internal/utils/volume_helper.go
  internal/utils/volumehelper_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#310 Expose module's name and namespace
  Makefile
  ci/module-kmm-ci-build-sign.yaml
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/module/kernelmapper.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#320 Patch instead of update Module and ManagedClusterModule status
  api-hub/v1beta1/managedclustermodule_types.go
  api/v1beta1/module_types.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#324 Fix signing Dockerfile
  .github/actions/collect-troubleshooting/action.yml
  .github/workflows/e2e.yaml
  Makefile
  ci/install-ci/kustomization.yaml
  internal/sign/job/signer_test.go
  internal/sign/job/templates/Dockerfile.gotmpl
Labels: size/M, approved, lgtm, cncf-cla: yes

#327 Adding Version field to Module CRD
  api/v1beta1/module_types.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#329 Build binaries manually for CodeQL
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, cncf-cla: yes, size/S

#330 Adding module version labels definitions
  internal/constants/constants.go
  internal/utils/moduleversionlabels.go
  internal/utils/moduleversionlabels_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#332 Refactoring of handleDriverContainer code
  controllers/mock_module_reconciler.go
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  go.mod
  go.sum
  internal/build/job/maker.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/sign/job/signer.go
  internal/statusupdater/mock_statusupdater.go
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#338 Update broken links in secure_boot.md
  docs/mkdocs/documentation/secure_boot.md
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test, kind/documentation

#328 Adding the namespace to the `<module>.ready` label.
  controllers/pod_node_module_reconciler.go
  controllers/pod_node_module_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#334 handling Version change in DevicePlugin and ModuleLoader DaemonSets
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/api/moduleloaderdata.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/module/kernelmapper.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#346 Require Go 1.19 and bump dependencies
  .github/workflows/codeql-analysis.yml
  Makefile
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  go.mod
  go.sum
  internal/registry/registry_helper_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#352 updating skipper dockerfile base image to golang-1.19
  Dockerfile.kmm-operator-build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#357 Revert "Adding a `prow` script to test a basic deployment."
  ci/prow/test-deploy
Labels: size/XS, approved, lgtm, cncf-cla: yes

#356 fixing Daemonsets GC
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#358 Revert "Adding `cert-manager` to config/default."
  ci/install-ci/kustomization.yaml
  config/certmanager/certmanager.yaml
  config/certmanager/kustomization.yaml
  config/crd-hub/patches/webhook_in_managedclustermodules.yaml
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_managedclustermodules.yaml
  config/crd/patches/webhook_in_modules.yaml
  config/default-hub/kustomization.yaml
  config/default/kustomization.yaml
  config/manager-base/manager.yaml
  config/manager-base/manager_auth_proxy_patch.yaml
  config/manager-base/manager_config_patch.yaml
  config/manifests-hub/kustomization.yaml
  config/manifests/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac-base/auth_proxy_role_binding.yaml
  config/rbac-base/auth_proxy_service.yaml
  config/rbac-base/kustomization.yaml
  config/rbac-base/leader_election_role_binding.yaml
  config/rbac-base/role_binding.yaml
  config/rbac-base/service_account.yaml
  config/rbac-hub/kustomization.yaml
  config/rbac/kustomization.yaml
  config/scorecard/kustomization.yaml
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#359 Installing `cert-manager` as part of the deployment.
  Makefile
  config/default/kustomization.yaml
  config/kmm/kustomization.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#360 Making sure that `cert-manager` is ready before deploying KMM.
  .gitignore
  Makefile
  README.md
  config/default/kustomization.yaml
  config/kmm/kustomization.yaml
  docs/mkdocs/documentation/install.md
  docs/mkdocs/documentation/uninstall.md
Labels: size/L, approved, lgtm, cncf-cla: yes

#354 In-tree kernel module replacement
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  internal/api/moduleloaderdata.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#348 Create a validation webhook
  Makefile
  PROJECT
  api/v1beta1/module_webhook.go
  api/v1beta1/module_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  ci/prow/e2e-incluster-build
  cmd/manager/main.go
  config/certificate/certificate.yaml
  config/certificate/kustomization.yaml
  config/certificate/kustomizeconfig.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test
