Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-08, with the labels that each got.

#500 Move to a maintained fork of gomock
  Makefile
  controllers/hub/managedclustermodule_reconciler_test.go
  controllers/mock_module_reconciler.go
  controllers/mock_node_label_module_version_reconciler.go
  controllers/module_reconciler_test.go
  controllers/node_kernel_clusterclaim_test.go
  controllers/node_kernel_reconciler_test.go
  controllers/node_label_module_version_reconciler_test.go
  controllers/pod_node_module_reconciler_test.go
  controllers/preflightvalidation_reconciler_test.go
  go.mod
  go.sum
  internal/auth/auth_test.go
  internal/auth/mock_auth.go
  internal/build/job/maker_test.go
  internal/build/job/manager_test.go
  internal/build/job/mock_maker.go
  internal/build/mock_helper.go
  internal/build/mock_manager.go
  internal/cache/mock_cache.go
  internal/client/mock_client.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster.go
  internal/cluster/suite_test.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/filter/filter_test.go
  internal/manifestwork/manifestwork_test.go
  internal/manifestwork/mock_manifestwork.go
  internal/metrics/mock_metrics_api.go
  internal/module/helper_test.go
  internal/module/kernelmapper_test.go
  internal/module/mock_kernelmapper.go
  internal/nmc/helper_test.go
  internal/nmc/mock_helper.go
  internal/preflight/mock_preflight_api.go
  internal/preflight/preflight_test.go
  internal/registry/mock_registry_api.go
  internal/registry/registry_test.go
  internal/sign/job/manager_test.go
  internal/sign/job/mock_signer.go
  internal/sign/job/signer_test.go
  internal/sign/mock_helper.go
  internal/sign/mock_manager.go
  internal/statusupdater/mock_statusupdater.go
  internal/statusupdater/statusupdater_test.go
  internal/utils/jobhelper_test.go
  internal/utils/mock_jobhelper.go
  internal/worker/mock_imagepuller.go
  internal/worker/mock_modprobe.go
  internal/worker/worker_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#498 Require Go to 1.20 in go.mod
  go.mod
Labels: size/XS, approved, lgtm, cncf-cla: yes

#495 Introducing Module-to-NMC reconciliation logic
  Dockerfile.kmm-operator-build
  api/v1beta1/nodemodulesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfig.yaml
  config/rbac/role.yaml
  controllers/module_reconciler.go
  internal/filter/filter.go
  internal/nmc/helper.go
  internal/nmc/helper_test.go
  internal/nmc/mock_helper.go
  internal/nmc/mock_module_nmc.go
  internal/nmc/module_nmc.go
  internal/nmc/module_nmc_test.go
  internal/utils/nodeutils.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#502 Adding NotFound error to the GetMLD API
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#503 Introducing Module-NMC controller
  cmd/manager-hub/main.go
  cmd/manager/main.go
  config/rbac/role.yaml
  controllers/mock_module_nmc_reconciler.go
  controllers/module_nmc_reconciler.go
  controllers/module_nmc_reconciler_test.go
  controllers/module_reconciler.go
  internal/filter/filter.go
  internal/filter/filter_test.go
  internal/nmc/mock_module_nmc.go
  internal/nmc/module_nmc.go
  internal/nmc/module_nmc_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#518 Module deleted scenario in Module-NMC controller
  controllers/mock_module_nmc_reconciler.go
  controllers/module_nmc_reconciler.go
  controllers/module_nmc_reconciler_test.go
  controllers/pod_node_module_reconciler_test.go
  internal/constants/constants.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#513 Add the NodeModulesConfig controller
  api/v1beta1/nodemodulesconfig_types.go
  cmd/manager/main.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  config/manager/kustomization.yaml
  config/manager/manager_worker_image_patch.yaml
  config/rbac/role.yaml
  controllers/mock_nodemodulesconfig_reconciler.go
  controllers/module_nmc_reconciler.go
  controllers/nodemodulesconfig_reconciler.go
  controllers/nodemodulesconfig_reconciler_test.go
  go.mod
  go.sum
  internal/cmd/cmdutils.go
  internal/filter/filter.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#523 Fixing panic in case worker pod has failed
  controllers/nodemodulesconfig_reconciler.go
  controllers/nodemodulesconfig_reconciler_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#530 Fixing Unloading Kmod on a previously failed Load Pod
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/nmc/helper.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#532 Adding Makefile target for worker image creation
  .gitignore
  Makefile
  skipper.env
Labels: size/XS, approved, lgtm, cncf-cla: yes

#537 Reconfigure worker pod capabilities
  Dockerfile.worker
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#539 Fixing Unload Pod not being created on Module deletion
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#540 Add pull secrets support for the worker
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cmd/worker/main.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/filter/filter_test.go
  internal/nmc/helper.go
  internal/nmc/helper_test.go
  internal/nmc/mock_helper.go
  internal/worker/constants.go
  internal/worker/imagepuller.go
  internal/worker/imagepuller_test.go
  internal/worker/pullsecrets.go
  internal/worker/pullsecrets_test.go
  internal/worker/testdata/pull-secrets/sub0/sub0sub/.dockerconfigjson
  internal/worker/testdata/pull-secrets/sub1/.dockercfg
  internal/worker/testdata/pull-secrets/sub2/random-file
  internal/worker/worker_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#544 Fixing panic for pull secret implementation
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#545 Fixing worker pod failure in case no pullsecrets are defined
  Dockerfile.worker
Labels: size/XS, approved, lgtm, cncf-cla: yes

#543 Adding Garbage Collection for NMC objects for deleted Nodes
  cmd/manager/main.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#546 Make the images directory a constant
  Dockerfile.worker
  cmd/worker/main.go
  internal/worker/constants.go
Labels: approved, lgtm, cncf-cla: yes, size/S
