Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-06, with the labels that each got.

#425 Set the tag of related images when building bundles
  Makefile
  ci/prow/check-api-changes
  cloudbuild.yaml
  config/manager-base/kustomization.yaml
  config/manager-base/kustomizeconfig.yaml
  config/manager-base/manager.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#426 Set the tag of all images when building bundles
  Makefile
  ci/prow/check-api-changes
  cloudbuild.yaml
  config/manager-base/kustomization.yaml
  config/manager-base/kustomizeconfig.yaml
  config/manager-base/manager.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#427 Fix a command in cloudbuild.yaml
  cloudbuild.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#428 Fix a command in cloudbuild.yaml
  cloudbuild.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#429 Inject the webhook CA into the validated CRDs
  config/crd-hub/kustomization.yml
  config/crd-hub/patches/cainjection_in_managedclustermodules.yaml
  config/crd-hub/patches/webhook_in_managedclustermodules.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_preflightvalidations.yaml
  config/crd/patches/webhook_in_preflightvalidations.yaml
  config/default-hub/kustomization.yaml
  config/default/kustomization.yaml
  config/manager-base/kustomization.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#432 Make cert-manager an OLM dependency of KMM
  Makefile
  config/manifests-hub/bundle-metadata/dependencies.yaml
  config/manifests/bundle-metadata/dependencies.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#431 Adding ordered upgrade documentation
  docs/mkdocs/documentation/ordered_upgrade.md
Labels: size/M, approved, lgtm, cncf-cla: yes

#438 Add 1.1 docs
  docs/mkdocs/documentation/deploy_kmod.md
  docs/mkdocs/documentation/install.md
  docs/mkdocs/documentation/module_loader_image.md
  docs/mkdocs/documentation/ordered_upgrade.md
Labels: size/L, approved, lgtm, cncf-cla: yes

#445 Enforce name and namespace length in the webhook
  api/v1beta1/module_webhook.go
  api/v1beta1/module_webhook_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#446 Do not require pods to have a `.spec.nodeName`
  controllers/pod_node_module_reconciler.go
  controllers/pod_node_module_reconciler_test.go
  internal/filter/filter.go
  internal/filter/filter_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#451 Replace deprecated command with environment file
  .github/actions/create-minikube-cluster/action.yml
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#302 Add a script generating files for OperatorHub.io
  CONTRIBUTING.md
  Makefile
  config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
  hack/release-operatorhub
Labels: size/L, approved, lgtm, cncf-cla: yes

#456 Quote arguments in modprobe commands
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#454 Upgrade support between v1.02 and v1.1
  controllers/mock_module_reconciler.go
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#457 Add further checks on Module version
  api/v1beta1/module_webhook.go
  api/v1beta1/module_webhook_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#459 Fix the ordered upgrade documentation
  docs/mkdocs/documentation/ordered_upgrade.md
Labels: size/M, approved, lgtm, cncf-cla: yes

#460 Add documentation for Hub & Spoke
  docs/mkdocs.yml
  docs/mkdocs/documentation/hub_spoke.md
  docs/mkdocs/documentation/install.md
Labels: size/L, approved, lgtm, cncf-cla: yes
