Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-07, with the labels that each got.

#464 Fixing ModuleLoader recreation during Node reboot
  internal/filter/filter.go
  internal/filter/filter_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#480 adding NodeModulesState type
  api/v1beta1/nodemodulestate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulestates.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#481 adding ModuleConfig struct to NodeModulesSpec
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfig.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulestates.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes

#463 Add a proposal for worker Pods in KMM
  docs/enhancements/0001-worker-pods.md
Labels: size/L, approved, lgtm, cncf-cla: yes

#494 Fix race condition for Node reboot issue
  controllers/module_reconciler.go
  internal/filter/filter.go
  internal/filter/filter_test.go
  internal/utils/nodeutils.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#496 Add Cloud Build configuration for the worker image
  cloudbuild.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#499 Document default DaemonSet image pull policy
  docs/mkdocs/documentation/deploy_kmod.md
Labels: size/M, approved, lgtm, cncf-cla: yes

#497 updating skipper Dockerfile to base image of Golang 1.20
  Dockerfile.kmm-operator-build
Labels: size/XS, approved, lgtm, cncf-cla: yes
