Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-12, with the labels that each got.

#657 Update ordered upgrade docs for v2
  docs/mkdocs/documentation/ordered_upgrade.md
Labels: size/M, approved, lgtm, cncf-cla: yes

#656 Docs typo - Use Cases - `module.name` not `module-name`
  docs/mkdocs/developer/use_cases.md
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#663 Bump client-go to v0.29.0
  cmd/worker/funcs_kmod_test.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  go.mod
  go.sum
  internal/build/pod/maker_test.go
  internal/config/config_test.go
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/sign/pod/signer_test.go
  internal/worker/imagepuller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#667 Bump `actions/{up,down}load-artifact`
  .github/workflows/e2e.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#668 Remove deprecated module ready labels on nodes
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/utils/kmmlabels.go
  internal/utils/kmmlabels_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#670 Fix handling of unknown kernels
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#672 Making GetModuleReady/GetDevicePluginReadyLabels functions public
  Dockerfile.kmm-operator-build
  pkg/labels/labels.go
  pkg/labels/labels_test.go
  pkg/labels/suite_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#673 Build / sign: handle all owner kinds
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/controllers/build_sign_events_reconciler.go
  internal/controllers/build_sign_events_reconciler_test.go
  internal/controllers/mock_build_sign_events_reconciler.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#677 Refactor worker to support different type of image to be mounted
  cmd/worker/funcs_kmod.go
  cmd/worker/main.go
  internal/worker/imagemounter.go
  internal/worker/mock_imagemounter.go
  internal/worker/mock_imagepuller.go
  internal/worker/remoteimagemounter.go
  internal/worker/remoteimagemounter_test.go
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes
