Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-05, with the labels that each got.

#381 Loading multiple independent kernel modules in one KMM Module
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#393 Upgrade to controller-gen 0.12.0
  Makefile
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
  config/rbac-hub/role.yaml
  config/rbac/role.yaml
  config/webhook-hub/manifests.yaml
  config/webhook/manifests.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#389 Changing InTree kernel module removal
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  internal/api/moduleloaderdata.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#397 Mount the prefixed secret in the Hub
  config/default-hub/kustomization.yaml
  config/default-hub/kustomizeconfig.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#403 Use ubuntu-20.04 explicitly in CI e2e tests instead of ubuntu-latest
  .github/workflows/e2e.yaml
  ci/kmm-kmod-dockerfile.yaml
Labels: cncf-cla: yes, size/S

#404 Update CI e2e-hub test
  .github/workflows/e2e.yaml
  ci/prow/e2e-hub-spoke-incluster-build
Labels: cncf-cla: yes, size/S

#407 Fix the cache key for binaries in CI
  .github/workflows/e2e.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#406 Make mresvanis a reviewer and an approver
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#392 Hub & Spoke: Expand and replace Module kernel mappings with literal ones before applying the ManifestWork
  cmd/manager-hub/main.go
  controllers/hub/managedclustermodule_reconciler.go
  controllers/hub/managedclustermodule_reconciler_test.go
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/cache/mock_cache.go
  internal/cache/suite_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster.go
  internal/manifestwork/manifestwork.go
  internal/manifestwork/manifestwork_test.go
  internal/manifestwork/mock_manifestwork.go
  internal/module/helper.go
  internal/module/helper_test.go
  internal/module/kernelmapper_test.go
  internal/registry/mock_registry_api.go
  internal/registry/registry.go
  internal/registry/registry_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#409 Add KERNEL_FULL_VERSION as a default build argument
  internal/build/job/maker.go
  internal/build/job/maker_test.go
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#411 Collect a support bundle in CI
  .github/actions/collect-troubleshooting/action.yml
  config/default-hub/kustomization.yaml
  config/default/kustomization.yaml
  support/kmm.spec.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#410 Use operator namespace when hub fetches the image digest
  cmd/manager-hub/main.go
  internal/manifestwork/manifestwork.go
  internal/manifestwork/manifestwork_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#422 Update skipper configuration
  Dockerfile.kmm-operator-build
Labels: size/XS, approved, lgtm, cncf-cla: yes
