Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-04, with the labels that each got.

#347 Module version nodes' label management
  cmd/manager/main.go
  controllers/mock_node_label_module_version_reconciler.go
  controllers/module_version_label_action_table.go
  controllers/node_label_module_version_reconciler.go
  controllers/node_label_module_version_reconciler_test.go
  internal/constants/constants.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/filter/filter.go
  internal/utils/moduleversionlabels.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#367 change the name of skipper build container to kmm-operator-build
  skipper.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#311 Define new selector for building image job
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  internal/build/job/maker.go
  internal/build/job/maker_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#379 Fixing termination timeout for module loader pods
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#380 Adding api for ordered multiple kernel modules
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#383 Prefix the webhook secret name with kmm-operator-
  config/certificate/kustomizeconfig.yaml
  config/default/kustomization.yaml
  config/default/kustomizeconfig.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S
