Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-10, with the labels that each got.

#587 Set resources for worker Pods
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#583 Record kmod load & unload events
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/utils/kmmlabels.go
  internal/utils/kmmlabels_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#588 Allow worker pods to restart on failures
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#589 Rename `JobEventReconciler` to `BuildSignEventsReconciler`
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/controllers/build_sign_events_reconciler.go
  internal/controllers/build_sign_events_reconciler_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#590 Fixing Module with device-plugin finalization deadlock
  internal/controllers/mock_module_reconciler.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#586 Make the worker set `firmware_class.path`
  cmd/worker/funcs_kmod.go
  cmd/worker/funcs_kmod_test.go
  cmd/worker/main.go
  cmd/worker/suite_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/config.yaml
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/worker/config.go
  internal/worker/constants.go
  internal/worker/mock_config.go
  internal/worker/mock_worker.go
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#592 Fix device-plugin/worker pod labels validationsduring ordered-upgrade
  internal/controllers/mock_node_label_module_version_reconciler.go
  internal/controllers/node_label_module_version_reconciler.go
  internal/controllers/node_label_module_version_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#594 Test the soft dependencies feature in CI
  ci/module-kmm-ci-build-sign.yaml
  ci/prow/e2e-incluster-build
Labels: approved, lgtm, cncf-cla: yes, size/S

#596 Adding support for firmware loading
  cmd/worker/funcs_kmod.go
  cmd/worker/funcs_kmod_test.go
  cmd/worker/main.go
  go.mod
  go.sum
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/worker/constants.go
  internal/worker/mock_worker.go
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#597 Reverting RestartPolicy back to Never
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#593 Test the in-tree removal feature
  ci/module-kmm-ci-build-sign.yaml
  ci/prow/e2e-incluster-build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#599 Fixing 2 bugs related to failure scenarios
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#604 Install clusteradm v0.6.0
  ci/prow/e2e-hub-spoke-incluster-build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#602 Splitting Module reconcile into BuildSign and DevicePlugin reconcilers
  cmd/manager/main.go
  internal/controllers/build_sign_reconciler.go
  internal/controllers/build_sign_reconciler_test.go
  internal/controllers/device_plugin_pod_reconciler.go
  internal/controllers/device_plugin_pod_reconciler_test.go
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/mock_build_sign_reconciler.go
  internal/controllers/mock_device_plugin_reconciler.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/controllers/pod_node_module_reconciler_test.go
  internal/controllers/suite_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/daemonset/suite_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#606 adapting Device Plugin status report in Module to v.2
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#607 Update webhook validation for name+namespace length
  api/v1beta1/module_webhook.go
  api/v1beta1/module_webhook_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#608 adapting Device Plugin status report in Module to v.2
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#610 Restructure Worker Pod secrets' volumes' names
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#611 Update webhook validation for name+namespace length (#607)
  api/v1beta1/module_webhook.go
  api/v1beta1/module_webhook_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#612 Restructure Worker Pod secrets' volumes' names
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#609 Set the worker restart policy to `OnFailure`
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/nmc/helper_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#617 [release-2.0] Set the worker restart policy to OnFailure
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/nmc/helper_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#621 adapting Worker Pods status report in Module to v.2 (#619)
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/nmc/helper.go
  internal/nmc/helper_test.go
  internal/nmc/mock_helper.go
Labels: size/L, approved, lgtm, cncf-cla: yes
