Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-01, with the labels that each got.

#223 Fix the Cloud Build config
  cloudbuild.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#220 Making the e2e-incluster-build job to actually build in cluster.
  .github/workflows/e2e.yaml
  ci/kmm-kmod-dockerfile.yaml
  ci/module-kmm-ci-build.template.yaml
  ci/prow/e2e-incluster-build
Labels: size/M, approved, lgtm, cncf-cla: yes

#225 changing the short name of the preflightvalidation CRD
  api/v1beta1/preflightvalidation_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#226 Configure related images via environment variables
  config/manager-base/manager.yaml
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#187 add support for KERNEL_VERSION replacement for signing
  internal/sign/helper.go
  internal/sign/helper_test.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
  internal/sign/mock_helper.go
  internal/utils/replaceStrings.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#224 Making the pre-built e2e test to use the in-cluster-build output.
  .github/actions/build-drivercontainer-image/action.yml
  .github/workflows/e2e.yaml
  ci/module-kmm-ci-build.yaml
  ci/module-kmm-ci-variable.yaml
  ci/module-kmm-ci.template.yaml
  ci/prow/e2e-crd-variable
  ci/prow/e2e-incluster-build
  ci/prow/e2e-prebuilt-kernel-module
  ci/prow/e2e-prebuilt-kernel-module-two-nodes
Labels: size/L, approved, lgtm, cncf-cla: yes

#227 Apply last-minute comments to PR 187
  internal/sign/helper_test.go
  internal/utils/replaceStrings.go
  internal/utils/replaceStrings_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#229 Adding preflight documentation
  docs/mkdocs/preflight/preflight-validation.md
Labels: size/L, approved, lgtm, cncf-cla: yes

#232 Adding back the `build-secret` to the e2e test.
  ci/module-kmm-ci-build.yaml
  ci/prow/e2e-incluster-build
Labels: approved, lgtm, cncf-cla: yes, size/S

#230 Implement ManagedClusterModuleStatus for KMM-Hub
  api-hub/v1beta1/managedclustermodule_types.go
  cmd/manager-hub/main.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  controllers/hub/managedclustermodule_reconciler.go
  controllers/hub/managedclustermodule_reconciler_test.go
  internal/manifestwork/manifestwork.go
  internal/manifestwork/manifestwork_test.go
  internal/manifestwork/mock_manifestwork.go
  internal/statusupdater/mock_statusupdater.go
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#207 Configure the ManifestWork to report the Module.Status
  internal/manifestwork/manifestwork.go
  internal/manifestwork/manifestwork_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#217 Improve push/pull secret handling in signing
  cmd/signimage/signimage.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
  internal/utils/volume_helper.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#234 Adjust ManagedClusterModuleReconciler ManagedCluster watch predicate
  controllers/hub/managedclustermodule_reconciler.go
  controllers/node_kernel_clusterclaim.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/constants/constants.go
  internal/filter/filter.go
  internal/filter/filter_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#236 Updating the `in-cluster-build` job to correctly use build secrets.
  ci/kmm-kmod-dockerfile.yaml
  ci/prow/e2e-incluster-build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#237 log error if sign-file fails
  cmd/signimage/signimage.go
  internal/sign/job/signer_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#242 Fix preflight documentation
  docs/mkdocs/preflight/preflight-validation.md
Labels: size/XS, approved, lgtm, cncf-cla: yes

#239 Adjust formatting, typos, etc
  docs/mkdocs.yml
  docs/mkdocs/developer/index.md
  docs/mkdocs/developer/reconciliation_loops.md
  docs/mkdocs/developer/use_cases.md
  docs/mkdocs/index.md
  docs/mkdocs/module_loaders.md
  docs/mkdocs/preflight/preflight-validation.md
  docs/mkdocs/secureboot/debugging.md
  docs/mkdocs/secureboot/index.md
  docs/mkdocs/secureboot/secureboot-build-and-sign.md
  docs/mkdocs/secureboot/secureboot-secrets.md
  docs/mkdocs/secureboot/secureboot-signing.md
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#235 Add all docs to the website
  docs/labs/aws/kmm-kmod.yaml
  docs/labs/azure/kmm-kmod.yaml
  docs/labs/gke/gke-ubuntu-nodes.yaml
  docs/labs/ubuntu/kmm-kmod.yaml
  docs/mkdocs.yml
  docs/mkdocs/documentation/deploy_kmod.md
  docs/mkdocs/documentation/firmwares.md
  docs/mkdocs/documentation/install.md
  docs/mkdocs/documentation/module_loader_image.md
  docs/mkdocs/documentation/preflight_validation.md
  docs/mkdocs/documentation/secure_boot.md
  docs/mkdocs/documentation/uninstall.md
  docs/mkdocs/module_loaders.md
  docs/mkdocs/preflight/preflight-validation.md
  docs/mkdocs/secureboot/debugging.md
  docs/mkdocs/secureboot/index.md
  docs/mkdocs/secureboot/secureboot-build-and-sign.md
  docs/mkdocs/secureboot/secureboot-secrets.md
  docs/mkdocs/secureboot/secureboot-signing.md
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#248 Add GarbageCollector for successful Sign job
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/sign/job/manager.go
  internal/sign/job/manager_test.go
  internal/sign/manager.go
  internal/sign/mock_manager.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#252 Fix a typo in the PreflightValidation CRD
  api/v1beta1/preflightvalidation_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#251 Ignore not-found errors on Pod finalizer update
  controllers/pod_node_module_reconciler.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#250 Configuring the build and sign job backoff and restart policies
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#215 Bump Kubernetes dependencies
  .github/workflows/e2e.yaml
  .github/workflows/test-codecov.yml
  Makefile
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  controllers/preflightvalidation_reconciler.go
  controllers/preflightvalidation_reconciler_test.go
  go.mod
  go.sum
  internal/client/mock_client.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/manifestwork/manifestwork.go
  internal/module/kernelmapper_test.go
  internal/statusupdater/mock_statusupdater.go
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#262 Fix grammar and markdown syntax in docs
  docs/mkdocs/documentation/deploy_kmod.md
  docs/mkdocs/documentation/preflight_validation.md
Labels: size/M, approved, lgtm, cncf-cla: yes

#211 Add README.md to docs
  docs/mkdocs/index.md
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#266 Do not create ServiceAccounts
  api-hub/v1beta1/managedclustermodule_types.go
  cmd/manager-hub/main.go
  cmd/manager/main.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/manager-base/manager.yaml
  config/manager-hub/kustomization.yaml
  config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml
  config/rbac/device_plugin_service_account.yaml
  config/rbac/kustomization.yaml
  config/rbac/module_loader_service_account.yaml
  config/rbac/role.yaml
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cmd/cmdutils.go
  internal/constants/constants.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/rbac/mock_rbac.go
  internal/rbac/rbac.go
  internal/rbac/rbac_test.go
  internal/rbac/suite_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#268 Fix Hub build and sign flow
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#270 Fixing `check-commits-count` to work on other branches than `main`.
  ci/prow/check-commits-count
Labels: size/XS, approved, lgtm, cncf-cla: yes

#275 Fixing documentation
  docs/mkdocs/developer/index.md
  docs/mkdocs/developer/use_cases.md
Labels: approved, lgtm, cncf-cla: yes, size/S
