Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-02, with the labels that each got.

#276 Fix KMM Hub scheme and permissions
  cmd/manager-hub/main.go
  cmd/manager/main.go
  config/rbac-hub/role.yaml
  controllers/hub/managedclustermodule_reconciler.go
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#279 Mention Pod Security Admission in the docs
  docs/mkdocs/documentation/deploy_kmod.md
Labels: approved, lgtm, cncf-cla: yes, size/S

#281 Add a troubleshooting section
  docs/.nojekyll
  docs/index.html
  docs/mkdocs.yml
  docs/mkdocs/documentation/troubleshooting.md
Labels: approved, lgtm, cncf-cla: yes, size/S

#280 Remove unnecessary ServiceAccounts used in the operator namespace
  config/rbac/device_plugin_service_account.yaml
  config/rbac/kustomization.yaml
  config/rbac/module_loader_service_account.yaml
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#288 Use a service for the registry
  .github/workflows/e2e.yaml
  ci/job-wait-minikube-registry-alias.yaml
  ci/module-kmm-ci-build.yaml
  ci/registry-nodeport.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#283 Move to Go 1.20
  .github/workflows/e2e.yaml
  .github/workflows/test-codecov.yml
  Dockerfile
  Dockerfile.signimage
  cloudbuild.yaml
  go.mod
Labels: approved, lgtm, cncf-cla: yes, size/S

#290 Wrap assertions into Ginkgo `It` blocks
  internal/utils/replaceStrings_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#287 Add signing to the e2e CI
  ci/module-kmm-ci-build-sign.yaml
  ci/prow/e2e-incluster-build
  ci/secret_kmm-kmod-signing.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#291 Move labs to the documentation website
  README.md
  docs/labs/README.md
  docs/mkdocs.yml
  docs/mkdocs/lab/aws/build-configmap.yaml
  docs/mkdocs/lab/aws/build-dkms-configmap.yaml
  docs/mkdocs/lab/aws/kmm-kmod.yaml
  docs/mkdocs/lab/azure/build-configmap.yaml
  docs/mkdocs/lab/azure/kmm-kmod.yaml
  docs/mkdocs/lab/gke/build-configmap.yaml
  docs/mkdocs/lab/gke/gke-ubuntu-nodes.yaml
  docs/mkdocs/lab/index.md
  docs/mkdocs/lab/ubuntu/build-module.yaml
  docs/mkdocs/lab/ubuntu/kmm-kmod.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#293 add manager-hub to .gitignore
  .gitignore
Labels: size/XS, approved, lgtm, cncf-cla: yes

#286 Fixes edit-uri for documentation
  docs/mkdocs.yml
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#278 Add {,un}deploy KMM Hub Makefile rules
  Makefile
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#292 Simplifying KernelAPI interface
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
  internal/module/mock_kernelmapper.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#299 Fix CSV metadata
  api-hub/v1beta1/managedclustermodule_types.go
  api/v1beta1/module_types.go
  api/v1beta1/preflightvalidation_types.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml
  config/manifests-hub/kustomization.yaml
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/samples-hub/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/samples-hub/kustomization.yml
  config/samples/kmm.sigs.x-k8s.io_modules.yaml
  config/samples/kmm.sigs.x-k8s.io_preflightvalidations.yaml
  config/samples/kustomization.yml
Labels: size/L, approved, lgtm, cncf-cla: yes

#301 Creating ModuleLoaderData sturcture for Build/Sign/ModuleLoader workflow
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  internal/api/moduleloaderdata.go
  internal/auth/auth.go
  internal/build/job/maker.go
  internal/build/job/maker_test.go
  internal/build/job/manager.go
  internal/build/job/manager_test.go
  internal/build/job/mock_maker.go
  internal/build/manager.go
  internal/build/mock_manager.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/module/helper.go
  internal/module/helper_test.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
  internal/module/mock_kernelmapper.go
  internal/preflight/mock_preflight_api.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/sign/job/manager.go
  internal/sign/job/manager_test.go
  internal/sign/job/mock_signer.go
  internal/sign/job/signer.go
  internal/sign/job/signer_test.go
  internal/sign/manager.go
  internal/sign/mock_manager.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#297 OGP
  docs/mkdocs.yml
  docs/mkdocs/index.md
  docs/overrides/main.html
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#306 Refactoring ModuleReconciler
  controllers/mock_module_reconciler.go
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#307 Changing the metrics flow
  cmd/manager/main.go
  controllers/module_reconciler.go
  controllers/module_reconciler_test.go
  controllers/preflightvalidation_reconciler.go
  controllers/preflightvalidation_reconciler_test.go
  internal/metrics/metrics.go
  internal/metrics/mock_metrics_api.go
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#308 Documentation fix
  docs/mkdocs/documentation/secure_boot.md
Labels: size/XS, approved, lgtm, cncf-cla: yes
