Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2023-09, with the labels that each got.

#521 Changing the Module-NMC reconciliation logic
  internal/constants/constants.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/nmc/helper.go
  internal/nmc/helper_test.go
  internal/utils/kmmlabels.go
  internal/utils/kmmlabels_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#548 Make all binaries run as regular users
  Dockerfile
  Dockerfile.worker
  cmd/manager/main.go
  config/manager-base/manager.yaml
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/config.yaml
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#551 Use the `default` ServiceAccount when creating NMC
  .github/workflows/e2e.yaml
  ci/install-ci-spoke/kustomization.yaml
  ci/install-ci/kustomization.yaml
  config/manager/controller_manager_config.yaml
  config/rbac/role.yaml
  internal/controllers/nmc_reconciler.go
  internal/nmc/helper.go
  internal/nmc/helper_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#552 Explicitly checking PodPending when reporting Build/Sign status
  internal/utils/podhelper.go
  internal/utils/podhelper_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#555 Update plantuml.jar download version and link
  docs.mk
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#556 Implementing ordered upgrade feature for V2
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/utils/kmmlabels.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#558 Changing daemonsets GarbageCollector for v2
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#563 Continuing adaption of ordered upgrade to KMM V2
  api/v1beta1/module_webhook_test.go
  internal/constants/constants.go
  internal/controllers/mock_node_label_module_version_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/controllers/module_version_label_action_table.go
  internal/controllers/node_label_module_version_reconciler.go
  internal/controllers/node_label_module_version_reconciler_test.go
  internal/utils/kmmlabels.go
  internal/utils/kmmlabels_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#567 Revert codecov action upgrade to v4
  .github/workflows/test-codecov.yml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#566 Changing the flow of SyncStatus to accomodate Delete Pod errors
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#569 Upgrade gomock to 0.3.0
  Makefile
  go.mod
  go.sum
  internal/auth/mock_auth.go
  internal/build/mock_helper.go
  internal/build/mock_manager.go
  internal/build/pod/mock_maker.go
  internal/cache/mock_cache.go
  internal/client/mock_client.go
  internal/cluster/mock_cluster.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/mock_module_reconciler.go
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/mock_node_label_module_version_reconciler.go
  internal/daemonset/mock_daemonset.go
  internal/manifestwork/mock_manifestwork.go
  internal/metrics/mock_metrics_api.go
  internal/module/mock_kernelmapper.go
  internal/nmc/mock_helper.go
  internal/preflight/mock_preflight_api.go
  internal/registry/mock_registry_api.go
  internal/sign/mock_helper.go
  internal/sign/mock_manager.go
  internal/sign/pod/mock_signer.go
  internal/statusupdater/mock_statusupdater.go
  internal/utils/mock_podhelper.go
  internal/worker/mock_imagepuller.go
  internal/worker/mock_modprobe.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#570 Upgrade to controller-runtime v0.16.2
  Makefile
  config/manager-base/kustomization.yaml
  config/manager-base/manager.yaml
  config/manager-base/manager_auth_proxy_patch.yaml
  config/manager-hub/controller_manager_config.yaml
  config/manager/controller_manager_config.yaml
  config/rbac-base/kustomization.yaml
  go.mod
  go.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/config.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes

#573 Record more fields into the NMC status
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#574 Code cleanup
  internal/constants/constants.go
  internal/controllers/module_nmc_reconciler_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#575 Handling of kmm module ready label (kernel module is loaded)
  Dockerfile.kmm-operator-build
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/utils/kmmlabels.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#579 Fix concurrent map read and write in cache test
  internal/cache/cache_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#580 Removing DaemonSet role from the DevicePlugin labels
  internal/constants/constants.go
  internal/controllers/node_label_module_version_reconciler.go
  internal/controllers/node_label_module_version_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#577 Publish build & sign events
  cmd/manager-hub/main.go
  cmd/manager/main.go
  config/rbac-base/event_recorder_clusterrole.yaml
  config/rbac-base/event_recorder_clusterrole_binding.yaml
  config/rbac-base/kustomization.yaml
  config/rbac-base/leader_election_role.yaml
  go.mod
  internal/build/pod/maker.go
  internal/build/pod/maker_test.go
  internal/constants/constants.go
  internal/controllers/job_event_reconciler.go
  internal/controllers/job_event_reconciler_test.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/filter/filter_test.go
  internal/meta/annotations.go
  internal/meta/annotations_test.go
  internal/meta/labels.go
  internal/meta/labels_test.go
  internal/meta/suite_test.go
  internal/sign/pod/signer.go
  internal/sign/pod/signer_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#584 Fix flaky async cache test
  internal/cache/cache_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S
