Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2024-06, with the labels that each got.

#825 Bump Kubernetes dependencies
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  go.mod
  go.sum
Labels: size/L, approved, lgtm, cncf-cla: yes

#824 Normalize kernel version in labels and image tags
  internal/api/moduleloaderdata.go
  internal/build/pod/maker.go
  internal/build/pod/maker_test.go
  internal/build/pod/manager.go
  internal/build/pod/manager_test.go
  internal/kernel/kernel.go
  internal/kernel/kernel_test.go
  internal/kernel/suite_test.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
  internal/sign/helper.go
  internal/sign/pod/manager.go
  internal/sign/pod/manager_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#827 Do not start `BuildSignReconciler` in managed mode
  cmd/manager/main.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#841 Release 2.1.1
  Dockerfile.signimage
  Dockerfile.worker
  cmd/manager/main.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  go.mod
  go.sum
  internal/api/moduleloaderdata.go
  internal/build/pod/maker.go
  internal/build/pod/maker_test.go
  internal/build/pod/manager.go
  internal/build/pod/manager_test.go
  internal/kernel/kernel.go
  internal/kernel/kernel_test.go
  internal/kernel/suite_test.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
  internal/sign/helper.go
  internal/sign/pod/manager.go
  internal/sign/pod/manager_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#844 Adding Node Package
  cmd/manager/main.go
  internal/controllers/build_sign_reconciler.go
  internal/controllers/build_sign_reconciler_test.go
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/mock_build_sign_reconciler.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/filter/filter.go
  internal/node/mock_node.go
  internal/node/node.go
  internal/node/node_test.go
  internal/node/suite_test.go
  internal/utils/kmmlabels.go
  internal/utils/nodeutils.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#845 adding unit tests to `node` package
  internal/node/node_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test
