Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2024-12, with the labels that each got.

#940 Add support for user defined tolerances to modules
  api/v1beta1/module_types.go
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/api/moduleloaderdata.go
  internal/build/pod/maker.go
  internal/controllers/build_sign_reconciler.go
  internal/controllers/build_sign_reconciler_test.go
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/filter/filter.go
  internal/module/kernelmapper.go
  internal/node/mock_node.go
  internal/node/node.go
  internal/node/node_test.go
  internal/sign/pod/signer.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#945 Fixing Module CR deletion during node reboot
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#944 Removing kmod labels without appropriate tolerations
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/node/mock_node.go
  internal/node/node.go
  internal/node/node_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#948 Making ImagePullPolicy in NMC optional
  api/v1beta1/nodemodulesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#958 Bumping `golang.org/x/net` to `v0.33.0`.
  go.mod
  go.sum
Labels: approved, lgtm, cncf-cla: yes, size/S

#957 Renaming the webhook deployment from `webhook-server` to `webhook`.
  ci/install-ci-hub/kustomization.yaml
  ci/install-ci/kustomization.yaml
  ci/prow/e2e-hub-spoke-incluster-build
  ci/prow/e2e-incluster-build
  ci/prow/operator-upgrade
  config/deploy-hub/kustomization.yaml
  config/deploy/kustomization.yaml
  config/webhook-cert/kustomization.yaml
  config/webhook-server/deployment.yaml
  docs/mkdocs/documentation/troubleshooting.md
Labels: approved, lgtm, cncf-cla: yes, size/S
