Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2024-11, with the labels that each got.

#925 Fixing handling ImageRepoSecret in worker pod
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#930 Fixing image repo secret extraction for unloading worker pod
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#933 Removing labels when node NotReady
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/node/mock_node.go
  internal/node/node.go
  internal/node/node_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test
