Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2024-08, with the labels that each got.

#871 Set a default value for `setFirmwareClassPath` in the worker config.
  config/manager/controller_config.yaml
  docs/mkdocs/documentation/configure.md
  docs/mkdocs/documentation/deploy_kmod.md
  docs/mkdocs/documentation/firmwares.md
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/worker/constants.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#873 Changing the FirmwarePath config flag
  config/manager/controller_config.yaml
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/config.yaml
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#874 Simplifying firmware flags between NMC controller and worker pod
  cmd/worker/funcs_kmod.go
  cmd/worker/funcs_kmod_test.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/worker/constants.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#887 Fixing some `kustomizeconfig.yaml` files.
  config/default-hub/kustomizeconfig.yaml
  config/default/kustomizeconfig.yaml
  config/webhook-cert/kustomizeconfig.yaml
  hack/download-kustomize
Labels: size/XS, approved, lgtm, cncf-cla: yes

#888 Updating deprecated `kustomization` fields.
  config/default-hub/kustomization.yaml
  config/default/kustomization.yaml
  config/manifests-hub/kustomization.yaml
  config/manifests/kustomization.yaml
  config/olm-hub/kustomization.yaml
  config/olm/kustomization.yaml
  config/webhook-server/kustomization.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#882 Bumping kubernetes and `controller-runtime` versions.
  Makefile
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
  config/rbac-hub/role.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XL, cncf-cla: yes
