Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2024-03, with the labels that each got.

#747 changing inTreeRemoval to support multiple modules
  api/v1beta1/module_types.go
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  ci/module-kmm-ci-build-sign.yaml
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/api/moduleloaderdata.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/controllers/nmc_reconciler_test.go
  internal/manifestwork/manifestwork.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
  internal/nmc/helper_test.go
  internal/webhook/module.go
  internal/webhook/module_test.go
  internal/worker/config_test.go
  internal/worker/testdata/config.yaml
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#754 Bring v2.0.2 commits
  Makefile
  api-hub/v1beta1/managedclustermodule_types.go
  api/v1beta1/module_types.go
  cmd/manager/main.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  config/rbac/role.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/manifests_namespace_selector_patch.yaml
  docs/mkdocs/documentation/deploy_kmod.md
  internal/constants/constants.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/meta/labels.go
  internal/webhook/namespace_deletion.go
  internal/webhook/namespace_deletion_test.go
  internal/webhook/suite_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#759 Getting the last published bundles from OLM instead of building it.
  .github/workflows/e2e.yaml
  ci/prow/operator-upgrade
Labels: size/M, approved, lgtm, cncf-cla: yes

#760 Handle `Module` namespace in `PreflightValidation`
  api/v1beta1/preflightvalidation_types.go
  api/v1beta1/preflightvalidation_types_test.go
  api/v1beta1/suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/groupversion_info.go
  api/v1beta2/preflightvalidation_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cmd/manager/main.go
  cmd/webhook-server/main.go
  config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_preflightvalidations.yaml
  config/default/kustomization.yaml
  internal/api/moduleloaderdata.go
  internal/controllers/build_sign_events_reconciler_test.go
  internal/controllers/preflightvalidation_reconciler.go
  internal/controllers/preflightvalidation_reconciler_test.go
  internal/filter/filter_test.go
  internal/preflight/mock_preflight_api.go
  internal/preflight/mock_statusupdater.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/preflight/statusupdater.go
  internal/preflight/statusupdater_test.go
  internal/preflight/test/modulestatus.go
  internal/preflight/test/modulestatus_test.go
  internal/statusupdater/mock_statusupdater.go
  internal/statusupdater/statusupdater.go
  internal/statusupdater/statusupdater_test.go
  internal/test/scheme.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#769 Rename the webhook service
  Makefile
  config/crd-hub/patches/webhook_in_managedclustermodules.yaml
  config/crd/patches/webhook_in_modules.yaml
  config/crd/patches/webhook_in_preflightvalidations.yaml
  config/default-hub/kustomization.yaml
  config/default/kustomization.yaml
  config/webhook-hub/kustomization.yaml
  config/webhook-hub/service.yaml
  config/webhook/kustomization.yaml
  config/webhook/service.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#770 OLM: do no use cert-manager
  Makefile
  config/certificate/kustomization.yaml
  config/crd-hub/kustomization.yml
  config/crd-hub/patches/cainjection_in_managedclustermodules.yaml
  config/crd-hub/patches/webhook_in_managedclustermodules.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_modules.yaml
  config/crd/patches/cainjection_in_preflightvalidations.yaml
  config/crd/patches/webhook_in_modules.yaml
  config/crd/patches/webhook_in_preflightvalidations.yaml
  config/default-hub/kustomization.yaml
  config/default-hub/webhookcainjection_patch.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/deploy-hub/kustomization.yaml
  config/deploy/kustomization.yaml
  config/manager-base/kustomizeconfig.yaml
  config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml
  config/manifests-hub/bundle-metadata/dependencies.yaml
  config/manifests-hub/kustomization.yaml
  config/manifests/bundle-metadata/dependencies.yaml
  config/manifests/kustomization.yaml
  config/webhook-cert/certificate.yaml
  config/webhook-cert/kustomization.yaml
  config/webhook-cert/kustomizeconfig.yaml
  config/webhook-hub/kustomization.yaml
  config/webhook-hub/kustomizeconfig.yaml
  config/webhook-hub/service.yaml
  config/webhook-server/deployment.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
  hack/download-kustomize
Labels: size/L, approved, lgtm, cncf-cla: yes

#775 `PreflightValidation`: populate old status keys
  api/v1beta1/preflightvalidation_types.go
  api/v1beta1/preflightvalidation_types_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes
