Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2024-09, with the labels that each got.

#886 Adding an init container to the worker pod.
  .github/workflows/e2e.yaml
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#895 Removing the `ImageMounter` interface.
  cmd/worker/funcs_kmod.go
  internal/worker/imagemounter.go
  internal/worker/imagemounter_test.go
  internal/worker/mock_imagemounter.go
  internal/worker/remoteimagemounter.go
  internal/worker/remoteimagemounter_test.go
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#899 Using the Module's `spec.moduleLoader.container.imagePullPolicy`.
  api/v1beta1/nodemodulesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#901 Introducing FileSystemHelper interface
  cmd/worker/funcs_kmod.go
  internal/utils/filesystem_helper.go
  internal/utils/filesystem_helper_test.go
  internal/utils/mock_filesystem_helper.go
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#902 Updating skipper image to correct GO version
  Dockerfile.kmm-operator-build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#905 Remove qbarrand from reviewers
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#911 Fixing module loading during kernel upgrade
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#912 Changing Node interface and updating NMC controller
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/node/mock_node.go
  internal/node/node.go
  internal/node/node_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#913 Fixing race condition during cluster upgrade with kernel upgrade
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes
