Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2024-01, with the labels that each got.

#679 Fixing DevicePlugin upgrade from v1.x to v2.x
  internal/constants/constants.go
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#680 Removing `ci/kmm-kmod/Dockerfile` from the CI files.
  ci/kmm-kmod/Dockerfile
Labels: approved, lgtm, cncf-cla: yes, size/S

#681 [release-2.0] Add commits for v2.0.1
  cmd/manager-hub/main.go
  cmd/manager/main.go
  cmd/worker/funcs_kmod.go
  cmd/worker/main.go
  internal/constants/constants.go
  internal/controllers/build_sign_events_reconciler.go
  internal/controllers/build_sign_events_reconciler_test.go
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/mock_build_sign_events_reconciler.go
  internal/controllers/module_nmc_reconciler.go
  internal/controllers/module_nmc_reconciler_test.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/utils/kmmlabels.go
  internal/utils/kmmlabels_test.go
  internal/worker/imagemounter.go
  internal/worker/mock_imagemounter.go
  internal/worker/mock_imagepuller.go
  internal/worker/remoteimagemounter.go
  internal/worker/remoteimagemounter_test.go
  internal/worker/worker.go
  internal/worker/worker_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#682 Extract links from kmod images
  go.mod
  go.sum
  internal/worker/remoteimagemounter.go
  internal/worker/remoteimagemounter_test.go
  internal/worker/testdata/archive.tar
Labels: approved, lgtm, size/XL, cncf-cla: yes

#683 Add extra label for controllers to install at worker nodes
  config/manager-base/manager.yaml
  docs/mkdocs/lab/index.md
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#686 Create a helper interface for mounting OCI images
  internal/worker/imagemounter.go
  internal/worker/imagemounter_test.go
  internal/worker/mock_imagemounter.go
  internal/worker/remoteimagemounter.go
  internal/worker/remoteimagemounter_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#689 Update docs to v2.0.1
  config/manager/controller_config.yaml
  docs/mkdocs.yml
  docs/mkdocs/documentation/configure.md
  docs/mkdocs/documentation/deploy_kmod.md
  docs/mkdocs/documentation/firmwares.md
  docs/mkdocs/documentation/hub_spoke.md
  docs/mkdocs/documentation/install.md
  docs/mkdocs/documentation/troubleshooting.md
Labels: size/L, approved, lgtm, cncf-cla: yes

#691 re-factoring worker's main and funcs_kmods
  cmd/worker/funcs_kmod.go
  cmd/worker/main.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#693 Adding an operator-upgrade Github workflow.
  .github/workflows/e2e.yaml
  ci/prow/operator-upgrade
Labels: size/L, approved, lgtm, cncf-cla: yes

#707 adding logs to worker flow of config read and set firmware path
  cmd/worker/funcs_kmod.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#714 Revert "Bump actions/cache from 3 to 4"
  .github/workflows/e2e.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#715 Revert "Adding an operator-upgrade Github workflow."
  .github/workflows/e2e.yaml
  ci/prow/operator-upgrade
Labels: size/L, approved, lgtm, cncf-cla: yes

#709 Add kmm and kmm-hub keywords to the CSV metadata
  config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml
  config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#716 Adding an operator-upgrade Github workflow.
  .github/workflows/e2e.yaml
  ci/prow/operator-upgrade
  support/kmm.spec.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#720 Allow the Hub to patch pods
  config/rbac-hub/role.yaml
  internal/controllers/hub/managedclustermodule_reconciler.go
Labels: size/XS, approved, lgtm, cncf-cla: yes
