Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2025-05, with the labels that each got.

#1084 Adding support for Modules with no OOT kmod
  api/v1beta1/module_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
  internal/controllers/hub/managedclustermodule_reconciler_test.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/manifestwork/manifestwork_test.go
  internal/module/kernelmapper_test.go
  internal/preflight/preflight_test.go
  internal/webhook/module.go
  internal/webhook/module_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#1095 Adding SkipWaitMissingImage field to MIC Spec
  api/v1beta1/moduleimagesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#1093 Update nmc node predicate to detect Ready transitions and meaningful changes
  internal/filter/filter.go
  internal/filter/filter_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#1096 Skip waiting for missing image in case the flag is set
  internal/controllers/mic_reconciler.go
  internal/controllers/mic_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1098 Allow KMM to be installed on worker nodes if there is no better choice.
  config/manager-base/manager.yaml
  config/webhook-server/deployment.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#1103 Removing old preflight implementation
  config/rbac/role.yaml
  internal/controllers/preflightvalidation_reconciler.go
  internal/controllers/preflightvalidation_reconciler_test.go
  internal/preflight/mock_preflight_api.go
  internal/preflight/mock_statusupdater.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/preflight/statusupdater.go
  internal/preflight/statusupdater_test.go
  internal/preflight/test/modulestatus.go
  internal/preflight/test/modulestatus_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1102 Gathering kmm RBAC annotations in Module controller
  internal/controllers/build_sign_reconciler.go
  internal/controllers/device_plugin_pod_reconciler.go
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/mbsc_reconciler.go
  internal/controllers/mic_reconciler.go
  internal/controllers/module_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/node_kernel_clusterclaim.go
  internal/controllers/node_label_module_version_reconciler.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1104 Removing the old build/sign packages and the old build-sign controller.
  internal/build/helper.go
  internal/build/helper_test.go
  internal/build/manager.go
  internal/build/mock_helper.go
  internal/build/mock_manager.go
  internal/build/pod/maker.go
  internal/build/pod/maker_test.go
  internal/build/pod/manager.go
  internal/build/pod/manager_test.go
  internal/build/pod/mock_maker.go
  internal/build/pod/suite_test.go
  internal/build/suite_test.go
  internal/cluster/suite_test.go
  internal/controllers/build_sign_reconciler.go
  internal/controllers/build_sign_reconciler_test.go
  internal/sign/helper.go
  internal/sign/helper_test.go
  internal/sign/manager.go
  internal/sign/mock_helper.go
  internal/sign/mock_manager.go
  internal/sign/pod/manager.go
  internal/sign/pod/manager_test.go
  internal/sign/pod/mock_signer.go
  internal/sign/pod/signer.go
  internal/sign/pod/signer_test.go
  internal/sign/pod/suite_test.go
  internal/sign/pod/templates/Dockerfile.gotmpl
  internal/sign/suite_test.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1111 Change Preflight VerifactionStatus and VerifactionStage definitions
  api/v1beta1/preflightvalidation_types.go
  api/v1beta2/preflightvalidation_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#1110 Reducing the `buildsign`'s porting layer.
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/buildsign/manager.go
  internal/buildsign/manager_test.go
  internal/buildsign/mock_buildsignresourcemanager.go
  internal/buildsign/mock_resourcemanager.go
  internal/buildsign/pod/buildsignpodmanager.go
  internal/buildsign/pod/common.go
  internal/buildsign/pod/manager.go
  internal/buildsign/pod/mock_buildsignpodmanager.go
  internal/buildsign/resource/common.go
  internal/buildsign/resource/common_test.go
  internal/buildsign/resource/resourcemanager.go
  internal/buildsign/resource/resourcemanager_test.go
  internal/buildsign/resource/suite_test.go
  internal/buildsign/resource/templates/Dockerfile.gotmpl
  internal/buildsign/resource/volumes.go
  internal/buildsign/resourcemanager.go
  internal/constants/constants.go
  internal/controllers/build_sign_events_reconciler.go
  internal/controllers/build_sign_events_reconciler_test.go
  internal/controllers/job_gc_reconciler.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1109 Deleting module.ImageExist and module.ImageDigest
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/auth/auth.go
  internal/auth/auth_test.go
  internal/auth/mock_auth.go
  internal/auth/suite_test.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/manifestwork/manifestwork.go
  internal/manifestwork/manifestwork_test.go
  internal/module/helper.go
  internal/module/helper_test.go
  internal/registry/mock_registry_api.go
  internal/registry/registry.go
  internal/registry/registry_helper_test.go
  internal/registry/registry_test.go
  internal/registry/suite_test.go
  internal/registry/testdata/image_manifest.json
Labels: approved, size/XXL, lgtm, cncf-cla: yes, ok-to-test

#1113 Adding preflight controller and enabling it in manager
  cmd/manager/main.go
  config/rbac/role.yaml
  internal/controllers/mock_preflightvalidation_reconciler.go
  internal/controllers/module_reconciler.go
  internal/controllers/preflightvalidation_reconciler.go
  internal/controllers/preflightvalidation_reconciler_test.go
  internal/preflight/mock_preflight.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1099 move GetRelevantBuild and GetRelevantSign from Combiner to kernelMapperHelperAPI
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/buildsign/resource/common.go
  internal/buildsign/resource/common_test.go
  internal/buildsign/resource/resourcemanager.go
  internal/buildsign/resource/resourcemanager_test.go
  internal/module/buildargoverrider.go
  internal/module/buildargoverrider_test.go
  internal/module/combiner.go
  internal/module/combiner_test.go
  internal/module/kernelmapper.go
  internal/module/kernelmapper_test.go
  internal/module/mock_buildargoverrider.go
  internal/module/mock_combiner.go
  internal/module/mock_kernelmapper.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#1114 Fixing logging warnings format.
  internal/buildsign/manager.go
  internal/controllers/hub/managedclustermodule_reconciler.go
  internal/controllers/mbsc_reconciler.go
  internal/controllers/module_reconciler.go
  internal/controllers/node_label_module_version_reconciler.go
  internal/worker/worker.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1116 Adding init container for device plugin implementation
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1117 Removing the `buildsignresourcemanager` mock.
  internal/buildsign/mock_buildsignresourcemanager.go
Labels: size/L, approved, lgtm, cncf-cla: yes
