Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2025-01, with the labels that each got.

#963 Bumping k8s APIs to `v0.32.0`.
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
  go.mod
  go.sum
Labels: size/L, approved, lgtm, cncf-cla: yes

#965 Bumping to `go1.23` in Github workflows (CI).
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e.yaml
  .github/workflows/test-codecov.yml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#970 Retrying applying CRs in the `e2e` jobs.
  ci/prow/e2e-hub-spoke-incluster-build
  ci/prow/e2e-incluster-build
Labels: size/XS, approved, lgtm, cncf-cla: yes

#969 Adding a `.` as a valid character for `Module`s' name.
  internal/nmc/labels.go
  internal/nmc/labels_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#971 adding ModuleImagesConfig definition
  Dockerfile.kmm-operator-build
  api/v1beta1/moduleimagesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#976 adding field needed for build and sign flow the MIC object
  api/v1beta1/moduleimagesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#979 Increasing the timeout for `cert-manager` deployments.
  Makefile
Labels: size/XS, approved, lgtm, cncf-cla: yes

#982 Renaming `module-nmc` controller to `module`.
  cmd/manager/main.go
  internal/controllers/mock_module_nmc_reconciler.go
  internal/controllers/mock_module_reconciler.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/filter/filter.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#986 Changing the Generation and ObservedGeneration
  api/v1beta1/moduleimagesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfig.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#987 Adding mbsc internal package
  internal/mbsc/mbsc.go
  internal/mbsc/mbsc_test.go
  internal/mbsc/mock_mbsc.go
  internal/mbsc/suite_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#991 Fixing toleration implementation
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/controllers/module_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/nmc/helper.go
  internal/nmc/helper_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#980 Removing cache package and image translation from Hub&Spoke flow
  cmd/manager-hub/main.go
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/cache/mock_cache.go
  internal/cache/suite_test.go
  internal/manifestwork/manifestwork.go
  internal/manifestwork/manifestwork_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#992 Adding `ModuleImagesConfig` and `ModuleBuildSignConfig` CRDs manifests.
  api/v1beta1/modulebuildsignconfig_types.go
  api/v1beta1/nodemodulesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd/kustomization.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#994 Adding tolerations specifications from Module to device plugin pods
  internal/controllers/device_plugin_reconciler.go
  internal/controllers/device_plugin_reconciler_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#996 Removing the `Generation` field from the `ModuleImagesConfigSpec`.
  api/v1beta1/moduleimagesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#995 Adding the `mic` package.
  internal/mic/mic.go
  internal/mic/mic_test.go
  internal/mic/mock_mic.go
  internal/mic/suite_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes
