Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2025-02, with the labels that each got.

#999 Adding new functions to MIC interface
  internal/mic/mic.go
  internal/mic/mic_test.go
  internal/mic/mock_mic.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1000 adding additional API to the mbsc package
  internal/mbsc/mbsc.go
  internal/mbsc/mbsc_test.go
  internal/mbsc/mock_mbsc.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#993 Generating `ModuleConfigImages` objects during `Module` reconciliation.
  cmd/manager/main.go
  config/rbac/role.yaml
  internal/controllers/mock_module_reconciler.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/filter/filter.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1003 Adding Patch API to mbsc package
  internal/mbsc/mbsc.go
  internal/mbsc/mbsc_test.go
  internal/mbsc/mock_mbsc.go
  internal/mbsc/suite_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1002 Creating MIC controller
  internal/controllers/mic_reconciler.go
  internal/controllers/mic_reconciler_test.go
  internal/controllers/mock_mic_reconciler.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1005 Changing the names of the APIs of mic package
  cmd/manager/main.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/mic/mic.go
  internal/mic/mic_test.go
  internal/mic/mock_mic.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1007 Adding action field to the MBSC image spec and changing logic accordingly
  api/v1beta1/modulebuildsignconfig_types.go
  api/v1beta1/moduleimagesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  internal/controllers/mic_reconciler.go
  internal/controllers/mic_reconciler_test.go
  internal/mbsc/mbsc.go
  internal/mbsc/mbsc_test.go
  internal/mbsc/mock_mbsc.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1010 Creating the `pod` package.
  internal/controllers/mic_reconciler.go
  internal/controllers/mic_reconciler_test.go
  internal/controllers/mock_mic_reconciler.go
  internal/pod/mock_pod.go
  internal/pod/pod.go
  internal/pod/pod_test.go
  internal/pod/suite_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1015 Adding GetImageSpec API to the mbsc package
  internal/mbsc/mbsc.go
  internal/mbsc/mbsc_test.go
  internal/mbsc/mock_mbsc.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1009 Creating mic resource also when images field is empty
  api/v1beta1/moduleimagesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
  internal/controllers/module_reconciler_test.go
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#1018 Changing MSBC image status structure
  api/v1beta1/modulebuildsignconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  internal/controllers/mic_reconciler.go
  internal/controllers/mic_reconciler_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1021 Adding KernelVersion to the MIC image spec
  api/v1beta1/moduleimagesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1024 Moving the `podManager` NMC helper interface to the new `pod` package.
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/build/manager.go
  internal/build/mock_manager.go
  internal/build/pod/maker.go
  internal/build/pod/maker_test.go
  internal/build/pod/manager.go
  internal/build/pod/manager_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/controllers/build_sign_events_reconciler.go
  internal/controllers/build_sign_events_reconciler_test.go
  internal/controllers/build_sign_reconciler.go
  internal/controllers/build_sign_reconciler_test.go
  internal/controllers/job_gc_reconciler.go
  internal/pod/buildsignpodmanager.go
  internal/pod/buildsignpodmanager_test.go
  internal/pod/mock_buildsignpodmanager.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/sign/manager.go
  internal/sign/mock_manager.go
  internal/sign/pod/manager.go
  internal/sign/pod/manager_test.go
  internal/sign/pod/signer.go
  internal/sign/pod/signer_test.go
  internal/utils/mock_podhelper.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1025 Un-exporting some of `WorkerPodManager` interface env variables.
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/pod/mock_workerpodmanager.go
  internal/pod/workerpodmanager.go
  internal/pod/workerpodmanager_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1027 Adding RegistryTLS to the MIC image spec
  api/v1beta1/moduleimagesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1028 Adding SetImageStatus API to mbsc package
  internal/mbsc/mbsc.go
  internal/mbsc/mbsc_test.go
  internal/mbsc/mock_mbsc.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1029 Prevent "Exists" tolerations from having a value
  internal/webhook/module.go
  internal/webhook/module_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#1030 Fixing buildsignpodmanager Status constants
  internal/pod/buildsignpodmanager.go
  internal/pod/buildsignpodmanager_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S
