Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2025-04, with the labels that each got.

#1061 BootID support for KMM
  api/v1beta1/nodemodulesconfig_types.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/controllers/mock_nmc_reconciler.go
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/node/mock_node.go
  internal/node/node.go
  internal/node/node_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test

#1066 Removing `LastTransitionTime` from the NMC status.
  api/v1beta1/nodemodulesconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/nmc/helper_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#1060 Switching KMM to work with the new build/sign flow
  cmd/manager/main.go
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  internal/controllers/mbsc_reconciler.go
  internal/controllers/mic_reconciler.go
  internal/controllers/module_reconciler.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1068 Reverting a config changes that was merged by mistake.
  config/manager/kustomization.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1070 Changing ImagePuller interface to more elaborate parameters
  internal/controllers/mic_reconciler.go
  internal/controllers/mic_reconciler_test.go
  internal/pod/imagepuller.go
  internal/pod/imagepuller_test.go
  internal/pod/mock_imagepuller.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1069 Start using `MIC` status to check if an image exists.
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/mic/mic.go
  internal/mic/mic_test.go
  internal/mic/mock_mic.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1079 Refactoring the way we generate volume/volumeMounts in build/sign flows.
  internal/buildsign/pod/buildsignpodmanager.go
  internal/buildsign/pod/buildsignpodmanager_test.go
  internal/buildsign/pod/common.go
  internal/buildsign/pod/volumes.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1080 Moving the volume methods from the `utils` to the `signpod` package.
  internal/sign/pod/signer.go
  internal/sign/pod/signer_test.go
  internal/utils/volume_helper.go
  internal/utils/volumehelper_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1082 Bumping the Github runners Ubuntu version.
  .github/workflows/e2e.yaml
  ci/kmm-kmod-dockerfile.yaml
  ci/prow/e2e-incluster-build
  docs/mkdocs/lab/gke/build-configmap.yaml
Labels: approved, lgtm, cncf-cla: yes, size/S

#1091 Remove non KMM related tolerations from the NMC status
  internal/controllers/nmc_reconciler.go
  internal/controllers/nmc_reconciler_test.go
  internal/pod/mock_workerpodmanager.go
  internal/pod/workerpodmanager.go
  internal/pod/workerpodmanager_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1092 Removed the `PodType` consts in the `buildsign` package.
  internal/build/pod/maker.go
  internal/build/pod/maker_test.go
  internal/build/pod/manager.go
  internal/build/pod/manager_test.go
  internal/buildsign/pod/buildsignpodmanager.go
  internal/buildsign/pod/buildsignpodmanager_test.go
  internal/buildsign/pod/manager.go
  internal/buildsign/pod/manager_test.go
  internal/controllers/build_sign_events_reconciler.go
  internal/controllers/build_sign_events_reconciler_test.go
  internal/controllers/job_gc_reconciler.go
  internal/sign/pod/manager.go
  internal/sign/pod/manager_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes
