Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2025-06, with the labels that each got.

#1097 Making KMM's configuration be persist during upgrade
  cmd/manager-hub/main.go
  cmd/manager/main.go
  cmd/webhook-server/main.go
  config/manager-base/kustomization.yaml
  config/manager-base/manager_config_patch.yaml
  config/manager-hub/kustomization.yaml
  config/manager-hub/manager_hub_config_patch.yaml
  config/manager/controller_config.yaml
  config/manager/kustomization.yaml
  config/manager/manager_config_patch.yaml
  config/webhook-server/deployment.yaml
  go.mod
  go.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/mock_config.go
  internal/config/testdata/config.yaml
  internal/config/testdata/hub-config.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#1119 Adding the `cp` requirement for kmod images documentation.
  docs/mkdocs/documentation/kmod_image.md
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1121 Fixing node events propagated to the module reconciler
  internal/filter/filter.go
  internal/filter/filter_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1123 Updating the `PreflightValidation` documentation.
  docs/mkdocs/documentation/preflight_validation.md
Labels: size/M, approved, lgtm, cncf-cla: yes

#1122 Documenting the new `initContainer` new option in the `DevicePlugin`.
  docs/mkdocs/documentation/deploy_kmod.md
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1127 propgate the pull policy from MOdule to ImagePuller pod
  internal/controllers/hub/managedclustermodule_reconciler.go
  internal/controllers/hub/managedclustermodule_reconciler_test.go
  internal/controllers/module_reconciler.go
  internal/controllers/module_reconciler_test.go
  internal/controllers/preflightvalidation_reconciler.go
  internal/controllers/preflightvalidation_reconciler_test.go
  internal/mic/mic.go
  internal/mic/mic_test.go
  internal/mic/mock_mic.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1132 Fixing the `GCDelay` configuration option default value documentation.
  docs/mkdocs/documentation/configure.md
  internal/config/config.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1134 Adding all KMM CRDs generated files to KMM-hub.
  Makefile
  config/crd-hub/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd-hub/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
  config/crd-hub/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd-hub/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
  config/crd-hub/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
  config/crd-hub/kustomization.yml
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1148 fixing HashAnnotationDiffer function potential bug
  internal/pod/workerpodmanager.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test
