Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2025-07, with the labels that each got.

#1152 Setting the cluster as a hub cluster.
  ci/prow/operator-hub-upgrade
Labels: approved, lgtm, cncf-cla: yes, size/S

#1151 Fixing KMM-hub's upgrade flow from 2.3.0 --> 2.4.0.
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/config/config.go
  internal/config/config_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1154 Introducing DockerfileOCIArtifact field to Module CRD.
  api/v1beta1/module_types.go
  config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
  config/crd-hub/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd-hub/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
  config/crd-hub/bases/kmm.sigs.x-k8s.io_modules.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
  config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1155 Adjusting webhook for shipwright builds
  go.mod
  internal/webhook/module.go
  internal/webhook/module_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes, ok-to-test
