Repository kubernetes-sigs/kernel-module-management, pull requests merged in 2025-03, with the labels that each got.

#1035 Moving BuildSignPodManager from the `pod` to the `buildsign` package
  cmd/manager-hub/main.go
  cmd/manager/main.go
  internal/build/manager.go
  internal/build/mock_manager.go
  internal/build/pod/maker.go
  internal/build/pod/maker_test.go
  internal/build/pod/manager.go
  internal/build/pod/manager_test.go
  internal/buildsign/pod/buildsignpodmanager.go
  internal/buildsign/pod/buildsignpodmanager_test.go
  internal/buildsign/pod/mock_buildsignpodmanager.go
  internal/buildsign/pod/suite_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/controllers/build_sign_events_reconciler.go
  internal/controllers/build_sign_events_reconciler_test.go
  internal/controllers/build_sign_reconciler.go
  internal/controllers/build_sign_reconciler_test.go
  internal/controllers/job_gc_reconciler.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
  internal/sign/manager.go
  internal/sign/mock_manager.go
  internal/sign/pod/manager.go
  internal/sign/pod/manager_test.go
  internal/sign/pod/signer.go
  internal/sign/pod/signer_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1036 bump build bundles to golang 1.23-alpine3.21
  cloudbuild.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1032 Adding manager and maker/signer to buildsign package
  internal/buildsign/manager.go
  internal/buildsign/mock_manager.go
  internal/buildsign/pod/maker.go
  internal/buildsign/pod/maker_test.go
  internal/buildsign/pod/manager.go
  internal/buildsign/pod/manager_test.go
  internal/buildsign/pod/mock_maker.go
  internal/buildsign/pod/mock_signer.go
  internal/buildsign/pod/signer.go
  internal/buildsign/pod/signer_test.go
  internal/buildsign/pod/templates/Dockerfile.gotmpl
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1037 Changing the GarbageCollector API of the buildsign manager
  internal/buildsign/manager.go
  internal/buildsign/mock_manager.go
  internal/buildsign/pod/manager.go
  internal/buildsign/pod/manager_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S

#1045 Adding GetImageStatus API to mbsc package
  internal/mbsc/mbsc.go
  internal/mbsc/mbsc_test.go
  internal/mbsc/mock_mbsc.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1047 Fixing MBSC object's owner creation
  internal/mbsc/mbsc.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1048 Updating image puller package with the new pod flow
  internal/pod/imagepuller.go
  internal/pod/imagepuller_test.go
  internal/pod/mock_imagepuller.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1049 Introducing MBSC controller
  config/rbac/role.yaml
  internal/controllers/mbsc_reconciler.go
  internal/controllers/mbsc_reconciler_test.go
  internal/controllers/mock_mbsc_reconciler.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1055 Aligning Sync API of the buildsign manager
  internal/buildsign/manager.go
  internal/buildsign/mock_manager.go
  internal/buildsign/pod/manager.go
  internal/buildsign/pod/manager_test.go
  internal/controllers/mbsc_reconciler.go
  internal/controllers/mbsc_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1054 Hiding the buildsign porting layer initialization
  internal/buildsign/pod/manager.go
  internal/buildsign/pod/manager_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1059 Filtering out node heartbeats events for the NMC controller.
  internal/controllers/nmc_reconciler.go
  internal/filter/filter.go
  internal/filter/filter_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1063 KMM Module should be Owner-Controller of MIC
  internal/mic/mic.go
  internal/mic/mic_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1065 Changing MIC controller to support new ImagePuller interface
  internal/controllers/mic_reconciler.go
  internal/controllers/mic_reconciler_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1064 Passing the MBSC object as an input to buildsign.Manager interface
  internal/controllers/mbsc_reconciler.go
  internal/controllers/mbsc_reconciler_test.go
Labels: approved, lgtm, cncf-cla: yes, size/S
